class_name GameConstants
extends RefCounted

const INTERACT_RANGE := 72.0
const MATE_RANGE := 100.0
const APPROACH_HINT_RANGE := 120.0
const PARTNER_IDLE_RANGE := 100.0
const PARTNER_GESTATION_STOP_RANGE := 44.0
const PARTNER_GESTATION_FOLLOW_SPEED := 78.0
const PARTNER_OFFSPRING_RANGE := 72.0
const PACK_SIZE_DECAY_SCALE := 0.12
const PACK_FEED_SHARE := 1.0
const PARTNER_NEEDS_DECAY_MULT := 0.85
const PREDATOR_PER_PACK_MEMBER := 1
const PREDATOR_AGGRO_RANGE := 200.0
const PREDATOR_BASE_COUNT := 6
const PREDATOR_MAX_COUNT := 10
const PREY_FLEE_RANGE := 150.0
const GESTATION_SECONDS := 30.0
const LITTER_SIZE_MIN := 1
const LITTER_SIZE_MAX := 3
const DEN_SAFE_RADIUS := 90.0
const DEN_STAY_RANGE := 220.0
const DEN_NEEDS_DECAY_MULT := 0.3
const RESOURCE_RESPAWN_SECONDS := 90.0
const DAY_CYCLE_SECONDS := 180.0
const GENERATION_DAMAGE_SCALE := 0.08
const GENERATION_SPEED_SCALE := 0.04
const GENERATION_NEEDS_SCALE := 0.03
const PLAYER_NEEDS_DECAY_MULT := 1.75
const HEIR_NEEDS_DECAY_MULT := 0.4
const HEIR_INDEPENDENCE_SECONDS := 50.0
const HEIR_ROGUE_AFTER_INDEPENDENCE_SECONDS := 70.0
const HEIR_INDEPENDENT_WANDER_MULT := 0.55
const HEIR_INDEPENDENT_NEEDS_DECAY_MULT := 1.0
const HEIR_ROGUE_DAMAGE := 14.0
const HEIR_ROGUE_ATTACK_COOLDOWN := 1.1
const ATTACK_COOLDOWN := 0.55
## Prototype toggle: no hunger/thirst gate for mating.
const MATE_REQUIRES_FED := false
